import { ClassPlanData } from "@/types/class-plan";

export const DUMMY_CLASS_PLANS: ClassPlanData[] = [
    {
        id: "CP-001",
        name: "Zumba Session",
        price: 100000,
        description: "High-energy Zumba class for all levels",
        minutesPerSession: 60,
        maxVisitor: 20,
        accessType: "regular",
        sessionSetting: {
            unlimitedDailySession: true,
            unlimitedMonthlySession: false,
            monthlyQuota: undefined,
            dailyQuota: 3,
        },
    },
    {
        id: "CP-002",
        name: "Boxing Class",
        price: 150000,
        description: "Boxing techniques and conditioning class",
        minutesPerSession: 75,
        maxVisitor: 15,
        accessType: "regular",
        sessionSetting: {
            unlimitedDailySession: false,
            unlimitedMonthlySession: false,
            monthlyQuota: undefined,
            dailyQuota: 2,
        },
    },
    {
        id: "CP-003",
        name: "CrossFit Training",
        price: 250000,
        description: "Intense CrossFit sessions for strength & endurance",
        minutesPerSession: 90,
        maxVisitor: 12,
        accessType: "premium",
        sessionSetting: {
            unlimitedDailySession: false,
            unlimitedMonthlySession: true,
            monthlyQuota: 20,
            dailyQuota: undefined,
        },
    },
    {
        id: "CP-004",
        name: "Body Pump",
        price: 200000,
        description: "Full-body strength workout using barbells",
        minutesPerSession: 60,
        maxVisitor: 18,
        accessType: "premium",
        sessionSetting: {
            unlimitedDailySession: true,
            unlimitedMonthlySession: true,
            monthlyQuota: undefined,
            dailyQuota: undefined,
        },
    },
    {
        id: "CP-005",
        name: "Pilates Class",
        price: 120000,
        description: "Pilates session to improve flexibility and core strength",
        minutesPerSession: 60,
        maxVisitor: 15,
        accessType: "regular",
        sessionSetting: {
            unlimitedDailySession: false,
            unlimitedMonthlySession: false,
            monthlyQuota: 15,
            dailyQuota: 2,
        },
    },
];
