import { ProductData } from "@/types/product";

export const DUMMY_PRODUCTS: ProductData[] = [
    {
        id: "GYM-001",
        name: "Protein Whey Chocolate 2lbs",
        sellingPrice: 750000,
        costPrice: 700000,
        stock: 25,
        category: "Supplements",
        image: undefined,
    },
    {
        id: "GYM-002",
        name: "BCAA Powder Lemon",
        sellingPrice: 420000,
        costPrice: 400000,
        stock: 18,
        category: "Supplements",
        image: undefined,
    },
    {
        id: "GYM-003",
        name: "Creatine Monohydrate 300g",
        sellingPrice: 380000,
        costPrice: 200000,
        stock: 20,
        category: "Supplements",
        image: undefined,
    },
    {
        id: "GYM-004",
        name: "Gym Gloves",
        sellingPrice: 150000,
        costPrice: 100000,
        stock: 40,
        category: "Accessories",
        image: undefined,
    },
    {
        id: "GYM-005",
        name: "Lifting Strap",
        sellingPrice: 90000,
        costPrice: 80000,
        stock: 50,
        category: "Accessories",
        image: undefined,
    },
    {
        id: "GYM-006",
        name: "Shaker Bottle 600ml",
        sellingPrice: 65000,
        costPrice: 50000,
        stock: 60,
        category: "Accessories",
        image: undefined,
    },
    {
        id: "GYM-007",
        name: "Resistance Band Set",
        sellingPrice: 220000,
        costPrice: 100000,
        stock: 30,
        category: "Equipment",
        image: undefined,
    },
    {
        id: "GYM-008",
        name: "Yoga Mat Anti-Slip",
        sellingPrice: 300000,
        costPrice: 200000,
        stock: 22,
        category: "Equipment",
        image: undefined,
    },
    {
        id: "GYM-009",
        name: "Gym Towel",
        sellingPrice: 85000,
        costPrice: 70000,
        stock: 70,
        category: "Merchandise",
        image: undefined,
    },
    {
        id: "GYM-010",
        name: "Membership Day Pass",
        sellingPrice: 100000,
        costPrice: 70000,
        stock: 9999,
        category: "Services",
        image: undefined,
    },
];
