import { PTSessionPlanData } from "@/types/pt-session-plan";

export const DUMMY_PT_SESSION_PLANS: PTSessionPlanData[] = [
    {
        id: "PTS-001",
        name: "Upper Body Womans",
        duration: 1,
        durationUnit: "day",
        price: 100000,
        description: "One day full access membership",
        minutesPerSession: 60,
        loyaltyPoint: 10,
        category: "Daily Visit",
        availabilitySetting: {
            unlimitedSold: true,
            quota: undefined,
            alwaysAvailable: true,
            availableFrom: undefined,
            availableUntil: undefined,
        },
    },
    {
        id: "PTS-002",
        name: "Lower Body Strength",
        duration: 3,
        durationUnit: "day",
        price: 250000,
        description: "3-day intensive lower body program",
        minutesPerSession: 75,
        loyaltyPoint: 25,
        category: "Short Program",
        availabilitySetting: {
            unlimitedSold: false,
            quota: 20,
            alwaysAvailable: false,
            availableFrom: "2026-01-10",
            availableUntil: "2026-01-20",
        },
    },
    {
        id: "PTS-003",
        name: "Full Body Transformation",
        duration: 30,
        durationUnit: "day",
        price: 1500000,
        description: "One month full body training with PT guidance",
        minutesPerSession: 90,
        loyaltyPoint: 150,
        category: "Monthly Plan",
        availabilitySetting: {
            unlimitedSold: true,
            quota: undefined,
            alwaysAvailable: true,
            availableFrom: undefined,
            availableUntil: undefined,
        },
    },
    {
        id: "PTS-004",
        name: "Cardio Booster",
        duration: 7,
        durationUnit: "day",
        price: 500000,
        description: "One-week cardio-focused sessions",
        minutesPerSession: 45,
        loyaltyPoint: 50,
        category: "Weekly Plan",
        availabilitySetting: {
            unlimitedSold: false,
            quota: 15,
            alwaysAvailable: false,
            availableFrom: "2026-01-5",
            availableUntil: "2026-01-12",
        },
    },
    {
        id: "PTS-005",
        name: "Strength & Conditioning",
        duration: 90,
        durationUnit: "day",
        price: 4000000,
        description: "3-month intensive strength and conditioning program",
        minutesPerSession: 120,
        loyaltyPoint: 400,
        category: "Quarterly Plan",
        availabilitySetting: {
            unlimitedSold: true,
            quota: undefined,
            alwaysAvailable: true,
            availableFrom: undefined,
            availableUntil: undefined,
        },
    },
];
